export const ADD_TWEET = 'ADD_TWEET';
export const ADD_LIKE_TWEET = 'ADD_LIKE_TWEET';
export const ADD_RETWEET = 'ADD_RETWEET';
export const RETWEET = 'RETWEET';
export const DELETE_TWEET = 'DELETE_TWEET';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
